app_sphere/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from app_sphere import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
0

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('search/', views.catalog, name='search'),
    path('product/<slug:product_slug>/', views.product, name='product'),
]

main/urls.py
from django.urls import path
import goods

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

goods/models.py
from email.policy import default
from unicodedata import category
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="goods_images", blank=True, null=True, verbose_name="Изображение"
    )
    price = models.DecimalField(
        default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена"
    )
    discount = models.DecimalField(
        default=0.00, max_digits=4, decimal_places=2, verbose_name="Скидка"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(
        to=Category, on_delete=models.CASCADE, verbose_name="Категория"
    )

    class Meta:
        db_table = "product"
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ("id",)

    def __str__(self):
        return f"{self.name} Количество - {self.quantity}"

main/models.py
from django.db import models

# Create your models here.
class Navigate(models.Model):

    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="main_images", blank=True, null=True, verbose_name="Изображение"
    )
    
    class Meta:
        db_table = "navigate"
        verbose_name = "Навигация"
        verbose_name_plural = "Навигации"

    
    def __str__(self):
        return self.name
    

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, render

from goods.models import Category, Products


def catalog(request, category_slug):

    page = request.GET.get("page", 1)
    on_sale = request.GET.get("on_sale", None)
    order = request.GET.get("order", None)

    if category_slug == "all":
        goods = Products.objects.all()
    else:
        goods = get_list_or_404(Products.objects.filter(category__slug=category_slug))

    if order:
        goods = goods.order_by(order)

    paginator = Paginator(goods, 4)
    current_page = paginator.get_page(page)

    context = {
        "title": "Каталог",
        "goods": current_page,
        "slug_url": category_slug,
    }
    return render(request, "goods/catalog.html", context)


def product(request, product_slug):

    product = Products.objects.get(slug=product_slug)

    context = {"product": product}

    return render(request, "goods/product.html", context=context)

main/views.py
from django.shortcuts import render

from goods.models import Category


def index(request):

    context = {
        'title': 'Главная', 
        'content': 'Группа компаний СФЕРА', 
    }  
          
    return render(request, 'main/index.html', context)


def about(request):
    context = {
        'title': 'О нас', 
        'content': 'Страница О нас',
        'text_on_page': 'текст о компании'
    }
    
    return render(request, 'main/about.html', context)


def contact(request):
    context = {
        'title': 'Контакты', 
        'content': 'Контакты',
        'text_on_page': 'Контакты компании'
    }
    
    return render(request, 'main/contact.html', context)

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% load goodstags %}

{% block content_left_col %} 
  <div class="container mx-2 pt-2">

    <form action="{% url "catalog:index" slug_url%}" metod="get" class="form-menu">
      <p class="text mx-3 mt-3">Фильтр</p>
      <div class="form-check  mx-5">
        <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" 
        {% if request.GET.on_sele == "on" %}checked{% endif %} disabled>
        {% comment "" %}<input type="hidden" name="q" value="request.GET.q">{% endcomment %}
        <label class="form-check-label" for="flexCheckDefault">
          Товары по акции
        </label>
      </div>
      <p class="text mx-3 mt-3">Сортировка по цене</p>
      <div class="form-check  mx-5">
        <input class="form-check-input" type="radio" name="order" id="flexRadioDefault1" value="-price" 
        {% if request.GET.order == "-price" %}checked{% endif %}>
        {% comment "" %}<input type="hidden" name="q" value="request.GET.q">{% endcomment %}
        <label class="form-check-label" for="flexRadioDefault1">
          по убыванию
        </label>
      </div>
      <div class="form-check mx-5 mt-3">
        <input class="form-check-input" type="radio" name="order" id="flexRadioDefault2" value="price" {% if request.GET.order == "price" %}checked{% endif %}>
        {% comment "" %}<input type="hidden" name="q" value="request.GET.q">{% endcomment %}
        <label class="form-check-label" for="flexRadioDefault2">
          по возрастанию
        </label>
      </div>
      <p class="text mx-3 mt-3"></p>
      <button type="submit" class="btn btn-primary mx-5 mt-3">Применить</button>
      <p class="text mx-3 mt-3"></p>
    </form>      
  </div>
      
    
{% endblock content_left_col %}

{% block content %}
  {% for product in goods %}
    <div class='col-lg-3 col-md-6 p-2'>
      <div class="card">
        {% if product.image %}
          <img src="{{ product.image.url }}" class="card-img-top" alt="{{product.name}}">
        {% else %}
          <img src="{% static "main/img/image_not_foutd.jpg" %}" class="card-img-top" alt="{{product.name}}">
        {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{product.name}}</h5>
            <p class="card-text">{{product.description}}</p>
            <p class="card-text">Цена: {{product.price}} руб</p>
            <a href="{% url "catalog:product" product.slug %}" class="btn btn-outline-success">Подробнее</a>
          </div>
      </div>
    </div>
  {% endfor %}
<!--Пагинация-->
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center pagination-lg">
    <li class="page-item {% if not goods.has_previous %} disabled {% endif %}">
      <a class="page-link" href="
      {% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}{% else %}
      #
      {% endif %}" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% for page in goods.paginator.page_range %}
    {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
      <li class="page-item {% if goods.number == page %} active {% endif %}">
        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
      </li>
    {% endif %}
    {% endfor %}
    
    <li class="page-item {% if not goods.has_next %} disabled {% endif %}">
      <a class="page-link" href="
      {% if goods.has_next %}?{% change_params page=goods.previous_page_number %}{% else %}
      #
      {% endif %}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      </a>
    </li> 
  </ul>
  </nav>
{% endblock content %}

goods/templates/goods/product.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <div class='container mt-5'>
        <div class='card mb-4'>
            <div class='row'>
                <!--Миниатюры-->
                <div class='col-md-4'>
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{product.name}}">
                    {% else %}
                        <img src="{% static "main/img/image_not_foutd.jpg" %}" class="card-img-top" alt="{{product.name}}">
                    {% endif %}
                </div>
                <div class=col-md-4>
                    <p>{{ product.description }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

</head>
<body>
    {% block content %}
        <h2 class="mt-5 pt-5">{{content}}</h2>
        <p>{{text_on_page}}</p>
    {% endblock content %}
            
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> 
</body>
</html>

main/templates/main/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "main/css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "main/css/style.css" %}>
    <title>{{title}}</title>
    <link rel="icon" href={% static "main/img/logo_title.PNG" %}>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body class="vh-100 overflow-hidden">
    <header>
      {% include "main/navigate.html" %}  
      <!--Навигация-->
       
    </header>

    <section>      
      <!--Блок контента-->
      <div class='container-fluid overflow-hidden text-center mt-4'>
        <div class='row'>
          <div class='col-lg-2'>
            <!--Контент левой колонки-->
            <div class="row">
              {% block content_left_col %}
              {% endblock content_left_col %}
            </div>
          </div>
          <div class='col-lg-8'>
            <!--Контент на странице-->
            <div class="row">
              {% block content %}
              {% endblock %}
            </div>
          </div> 
          <div class="col-lg-2">
            <!--пустой контенер с рекламой-->
          </div>         
        </div>
      </div>
    </section>

    <footer>
      {% block footer %}
      {% endblock footer %}
    </footer>
            
<script src={% static "main/js/bootstrap.bundle.min.js" %}></script> 
</body>
</html>

main/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}
    <h1 class="mt-5 pt-5">{{content}}</h1>
    <p class="mt-5 pt-5">{{text_on_page}}</p>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}
    <h1 class="mt-5 pt-5">{{content}}</h1>
{% endblock content %}

main/templates/main/navigate.html
{% load static %}
{% load goodstags %}

<nav class="navbar navbar-expand-lg navber-dark bg-transparent">
    <div class="container">
      <!--Логотип-->
      <a class="navbar-brand" href="{% url "main:index" %}">
        <img src="{% static "main/img/logo.PNG" %}" alt="logo" width="300" >
      </a>
      <!--Кнопка сворачивания меню-->
      <button 
        class="navbar-toggler shadow-none border-0" 
        type="button" 
        data-bs-toggle="offcanvas" 
        data-bs-target="#offcanvasNavbar" 
        aria-controls="offcanvasNavbar" 
        aria-label="Toggle navigation">

        <span class="navbar-toggler-icon"></span>
      </button>
      <!--Боковая Панель-->
      <div 
        class="sidebar offcanvas offcanvas-start" 
        tabindex="-1" 
        id="offcanvasNavbar" 
        aria-labelledby="offcanvasNavbarLabel">
      <!--Боковая Панель шапка-->
        <div class="offcanvas-header text-secondary border-bottom border-secondary">
          <h5 class="offcanvas-title" 
          id="offcanvasNavbarLabel">Offcanvas</h5>
          <button 
            type="button" 
            class="btn-close shadow-none" 
            data-bs-dismiss="offcanvas" 
            aria-label="Close">
          </button>
        </div>
        <!--Панель меню-->
        <div class="offcanvas-body d-flex flex-column flex-lg-row p-4">
          <ul class="navbar-nav nav-underline justify-content-center align-items-center fs-5 flex-grow-1 pe-3" id="myUnderline" role="underlist">
        
            <li class="nav-item" role="presentation">
              <a class="nav-link" href="{% url "main:index" %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "main:about" %}">Про нас</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "main:contact" %}">Контакты</a>
            </li> 
            {% comment "" %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "admin:index" %}">Админка</a>
            </li> 
            {% endcomment %}                 
            <!--Выпадающее меню-->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Каталог
              </a>
              <ul class="dropdown-menu">
                {% teg_category as categorys %}
                {% for category in categorys %}
                  <li><a class="dropdown-item" href="{% url "catalog:index" category.slug%}">{{category.name}}</a></li>   
                {% endfor %}
              </ul>
            </li>
          </ul>
          <!--Страка поиска и кнопка-->
          <form class="d-flex flex-column flex-lg-row p-4" role="search" action="{% url "catalog:search" %}" method="get">
            <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
          </form>
          <!--Логин / Войти-->
          <div class="d-flex flex-column justify-content-center align-items-center gap-3">
            <a href="#" 
            class="text-white text-decoration-none px-3 py-1 bg-secondary rounded-5"
            >Войти</a>
          </div>
        </div>
      </div>
    </div>
  </nav>